# 사이킷런 내장 예제 데이터

### 붓꽃 데이터 세트 기반의 ML 분류 예측 수행 프로세스

#### 사이킷런 기반 프레임워크 : Estimator 와 fit() / predict()
    
사이킷런에서 제공하는 메소드
- fit() : ML 모델 학습
- predict() : 학습된 모델의 예측

지도학습의 분류와 회귀에서 fit()과 predict()만 사용해서 간단하게 학습과 예측 결과 반환  
- 분류 알고리즘을 구현한 클래스 : Classifier
- 회귀 알고리즘을 구현한 클래스 : Regressor

Estimator 클래스 : Classifier + Regressor 클래스
- 지도학습의 모든 알고리즘을 구현한 크래스 통칭
- fit()과 predict() 내부에서 구현

### 사이킷런의 내장 데이터 세트 형태

#### 사이킷런의 내장 데이터 세트 형태
- key 구성 : data, target, target_names, feature_names, DESCR
- data : 피처 데이터 세트 (ndarry)
- target : 분류(레이블 값)/회귀(숫자 결과값 데이터 세트) (ndarry)
- target_names : 개별 레이블 이름 (ndarry 또는 list)
- feature_names : 피처 이름 (ndarry 또는 list)
- DESCR : 데이터 세트 설명, 각 피처 설명 (string)

#### 머신러닝 모델을 구축하는 주요 프로세스  
(1) 피처의 가공, 변경, 추출을 수행하는 피처 처리  
(2) ML 알고리즘 학습/예측 수행  
(3) 모델 평가
 - (1)(2)(3) 단계를 반복적으로 수행

### 붓꽃 데이터 세트 구성

In [4]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

# 타입 확인해봤더니 sklearn.utils.Bunch
# 파이썬의 딕셔너리와 유사 : key, value

<class 'sklearn.utils.Bunch'>


In [7]:
# 키 값 출력
keys = iris_data.keys()
print('붓꽃 데이터 세트의 key :\n', keys)

붓꽃 데이터 세트의 key :
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [10]:
# data 확인
print('data의 type :', type(iris_data.data))
print('data의 shape :', iris_data.data.shape)  # (150,4) 데이터 행 수, 피처 수
print(iris_data['data'])

data의 type : <class 'numpy.ndarray'>
data의 shape : (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3

In [11]:
# target 확인
print('target의 type :', type(iris_data.target))
print('target의 shape :', iris_data.target.shape) # 레이블 값 (150개)
print(iris_data.target)

target의 type : <class 'numpy.ndarray'>
target의 shape : (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [12]:
# 타깃 이름 확인 : target_names
print('target_names의 type :', type(iris_data.target_names))
print('target_names의 크기 :', len(iris_data.target_names))
print(iris_data.target_names)

target_names의 type : <class 'numpy.ndarray'>
target_names의 크기 : 3
['setosa' 'versicolor' 'virginica']


In [13]:
# 피처 이름 확인 feature_names
print('feature_names의 type :', type(iris_data.feature_names))
print('feature_names의 크기 :', len(iris_data.feature_names))
print(iris_data.feature_names)

feature_names의 type : <class 'list'>
feature_names의 크기 : 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [15]:
# 데이터 세트 설명 : 각 피처 설명 (string)
iris_data.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =